name = "laknah-cf"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "KV"
id = "6f20158dbe9e429f9c5b1ee30be79ef2"
